-- Enable TimescaleDB extension
-- This must run as a superuser (which the init container usually is)
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- System Tables
CREATE TABLE IF NOT EXISTS devices (
    name TEXT PRIMARY KEY,
    serial_number TEXT UNIQUE NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'offline',
    last_seen TIMESTAMPTZ,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    config JSON NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS system_services (
    name TEXT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    status TEXT NOT NULL DEFAULT 'stopped'
);

CREATE TABLE IF NOT EXISTS system_config (
    key TEXT PRIMARY KEY,
    value JSON NOT NULL
);

-- Data Tables
CREATE TABLE IF NOT EXISTS recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMPTZ NOT NULL,
    sensor_id TEXT NOT NULL REFERENCES devices(name),
    file_raw TEXT NOT NULL,
    file_processed TEXT NOT NULL,
    duration FLOAT NOT NULL,
    sample_rate INTEGER NOT NULL,
    filesize_raw BIGINT NOT NULL,
    filesize_processed BIGINT NOT NULL,
    uploaded BOOLEAN NOT NULL DEFAULT FALSE,
    uploaded_at TIMESTAMPTZ,
    analysis_state JSON NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS ix_recordings_time ON recordings (time);
CREATE INDEX IF NOT EXISTS ix_recordings_sensor_id ON recordings (sensor_id);
CREATE INDEX IF NOT EXISTS ix_recordings_uploaded ON recordings (uploaded);

CREATE TABLE IF NOT EXISTS uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    filename TEXT NOT NULL,
    size BIGINT NOT NULL,
    success BOOLEAN NOT NULL,
    error_message TEXT
);
CREATE INDEX IF NOT EXISTS ix_uploads_recording_id ON uploads (recording_id);

-- Hypertables (TimescaleDB)

-- Detections
CREATE TABLE IF NOT EXISTS detections (
    time TIMESTAMPTZ NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    end_time TIMESTAMPTZ NOT NULL,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    worker TEXT NOT NULL,
    confidence FLOAT NOT NULL,
    label TEXT NOT NULL,
    common_name TEXT,
    details JSON NOT NULL DEFAULT '{}',
    PRIMARY KEY (time, id)
);
CREATE INDEX IF NOT EXISTS ix_detections_worker ON detections (worker);
CREATE INDEX IF NOT EXISTS ix_detections_label ON detections (label);
CREATE INDEX IF NOT EXISTS ix_detections_recording_id ON detections (recording_id);

SELECT create_hypertable('detections', 'time', if_not_exists => TRUE);

-- Weather
CREATE TABLE IF NOT EXISTS weather (
    time TIMESTAMPTZ NOT NULL,
    source TEXT NOT NULL,
    station_code TEXT,
    temp_c FLOAT,
    humidity FLOAT,
    pressure_hpa FLOAT,
    wind_speed_kmh FLOAT,
    wind_gusts_kmh FLOAT,
    precipitation_mm FLOAT,
    cloud_cover INTEGER,
    uv_index FLOAT,
    sunshine_duration FLOAT,
    weather_code INTEGER,
    is_forecast BOOLEAN NOT NULL DEFAULT FALSE,
    extra JSON DEFAULT '{}',
    PRIMARY KEY (time, source)
);

SELECT create_hypertable('weather', 'time', if_not_exists => TRUE);
