-- 00-init-extensions.sql
-- Responsibility: Enable required extensions and set up initial permissions.
-- This runs as Superuser during the very first container initialization.

-- 1. Enable TimescaleDB (Core requirement)
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- 2. Ensure public schema exists (Standard Postgres behavior, but explicit is safer)
CREATE SCHEMA IF NOT EXISTS public;

-- 3. Optimization Note (Documentation)
-- The actual tables are NOT created here. They are managed by Alembic/SQLAlchemy
-- in the 'controller' or 'migration' service to allow for versioned schema evolution.
-- Silvasonic Initial Schema (Consolidated)
-- Replaces Alembic Migrations: 833e0e6f1e08, 20260202_varchar_text

-- 0. Microphone Profiles (New)
CREATE TABLE microphone_profiles (
    slug VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    match_pattern VARCHAR NOT NULL,
    config JSON NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (slug)
);

-- 1. Devices Table
CREATE TABLE devices (
    name TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL,
    enrollment_status TEXT NOT NULL DEFAULT 'pending',
    last_seen TIMESTAMP WITH TIME ZONE,
    enabled BOOLEAN NOT NULL,
    profile_slug VARCHAR,
    config JSON NOT NULL,
    PRIMARY KEY (name),
    UNIQUE (serial_number),
    FOREIGN KEY(profile_slug) REFERENCES microphone_profiles (slug)
);

-- 2. System Config
CREATE TABLE system_config (
    key TEXT NOT NULL,
    value JSON NOT NULL,
    PRIMARY KEY (key)
);

-- 3. System Services
CREATE TABLE system_services (
    name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    status TEXT NOT NULL,
    PRIMARY KEY (name)
);

-- 4. Taxonomy
CREATE TABLE taxonomy (
    worker TEXT NOT NULL,
    label TEXT NOT NULL,
    scientific_name TEXT NOT NULL,
    common_names JSON NOT NULL,
    description JSON NOT NULL,
    image_path TEXT,
    image_source TEXT,
    conservation_status TEXT,
    PRIMARY KEY (worker, label)
);

-- 5. Weather (Hypertable)
CREATE TABLE weather (
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    source TEXT NOT NULL,
    station_code TEXT,
    temp_c DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    pressure_hpa DOUBLE PRECISION,
    wind_speed_kmh DOUBLE PRECISION,
    wind_gusts_kmh DOUBLE PRECISION,
    precipitation_mm DOUBLE PRECISION,
    cloud_cover INTEGER,
    uv_index DOUBLE PRECISION,
    sunshine_duration DOUBLE PRECISION,
    weather_code INTEGER,
    is_forecast BOOLEAN NOT NULL,
    extra JSON NOT NULL,
    PRIMARY KEY (time, source)
);

-- 6. Recordings (Hypertable Candidate - but kept as standard table for FK constraints currently)
-- Note: Alembic had create_hypertable commented out because of FK issues. We keep it standard.
CREATE TABLE recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    sensor_id TEXT NOT NULL,
    file_raw TEXT NOT NULL,
    file_processed TEXT NOT NULL,
    duration DOUBLE PRECISION NOT NULL,
    sample_rate INTEGER NOT NULL,
    filesize_raw BIGINT NOT NULL,
    filesize_processed BIGINT NOT NULL,
    uploaded BOOLEAN NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE,
    analysis_state JSON NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(sensor_id) REFERENCES devices (name)
);
CREATE INDEX ix_recordings_time ON recordings (time);
CREATE INDEX ix_recordings_sensor_id ON recordings (sensor_id);
CREATE INDEX ix_recordings_uploaded ON recordings (uploaded);

-- 7. Detections (Hypertable)
CREATE TABLE detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    recording_id BIGINT NOT NULL,
    worker TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    label TEXT NOT NULL,
    common_name TEXT,
    details JSON NOT NULL,
    PRIMARY KEY (time, id),
    FOREIGN KEY(recording_id) REFERENCES recordings (id)
);
CREATE INDEX ix_detections_time ON detections (time);
CREATE INDEX ix_detections_label ON detections (label);
CREATE INDEX ix_detections_recording_id ON detections (recording_id);
CREATE INDEX ix_detections_worker ON detections (worker);

-- 8. Uploads
CREATE TABLE uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recording_id BIGINT NOT NULL,
    attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    filename TEXT NOT NULL,
    size BIGINT NOT NULL,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY(recording_id) REFERENCES recordings (id)
);
CREATE INDEX ix_uploads_recording_id ON uploads (recording_id);

-- 9. TimescaleDB Setup
SELECT create_hypertable('weather', 'time', if_not_exists => TRUE);
SELECT create_hypertable('detections', 'time', if_not_exists => TRUE);
