-- Silvasonic Initial Schema (Consolidated)
-- Replaces Alembic Migrations: 833e0e6f1e08, 20260202_varchar_text

-- 0. Microphone Profiles (New)
CREATE TABLE microphone_profiles (
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    match_pattern TEXT,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (slug)
);

-- 1. Devices Table
CREATE TABLE devices (
    name TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'offline',
    enrollment_status TEXT NOT NULL DEFAULT 'pending',
    last_seen TIMESTAMP WITH TIME ZONE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    profile_slug TEXT,
    config JSONB NOT NULL,
    workspace_name TEXT,
    PRIMARY KEY (name),
    UNIQUE (serial_number),
    UNIQUE (workspace_name),
    FOREIGN KEY(profile_slug) REFERENCES microphone_profiles (slug)
);

-- 2. System Config (ADR-0023: Configuration Management)
CREATE TABLE system_config (
    key TEXT NOT NULL,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (key)
);

-- 3. System Services
CREATE TABLE system_services (
    name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    status TEXT NOT NULL,
    PRIMARY KEY (name)
);

-- 4. Users (ADR-0023: Authentication)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (username)
);

-- 6. Taxonomy
CREATE TABLE taxonomy (
    worker TEXT NOT NULL,
    label TEXT NOT NULL,
    scientific_name TEXT NOT NULL,
    common_names JSONB NOT NULL,
    description JSONB NOT NULL,
    image_path TEXT,
    image_source TEXT,
    conservation_status TEXT,
    PRIMARY KEY (worker, label)
);

-- 7. Weather (Hypertable)
CREATE TABLE weather (
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    source TEXT NOT NULL,
    station_code TEXT,
    temp_c DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    pressure_hpa DOUBLE PRECISION,
    wind_speed_kmh DOUBLE PRECISION,
    wind_gusts_kmh DOUBLE PRECISION,
    precipitation_mm DOUBLE PRECISION,
    cloud_cover INTEGER,
    uv_index DOUBLE PRECISION,
    sunshine_duration DOUBLE PRECISION,
    weather_code INTEGER,
    is_forecast BOOLEAN NOT NULL,
    extra JSONB NOT NULL,
    PRIMARY KEY (time, source)
);

-- 8. Recordings (Standard Table — ADR-0025: No Hypertable)
-- Kept as standard table to preserve FK constraints from detections and uploads.
-- Data volume (~2M rows/year) does not require partitioning. See ADR-0025.
CREATE TABLE recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    sensor_id TEXT NOT NULL,
    file_raw TEXT NOT NULL,
    file_processed TEXT,
    duration DOUBLE PRECISION NOT NULL,
    sample_rate INTEGER NOT NULL,
    filesize_raw BIGINT NOT NULL,
    filesize_processed BIGINT NOT NULL DEFAULT 0,
    uploaded BOOLEAN NOT NULL DEFAULT FALSE,
    uploaded_at TIMESTAMP WITH TIME ZONE,
    local_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    analysis_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY(sensor_id) REFERENCES devices (name)
);
CREATE INDEX ix_recordings_time ON recordings (time);
CREATE INDEX ix_recordings_sensor_id ON recordings (sensor_id);

-- Worker Pull (ADR-0018): Analysis workers claim unprocessed recordings.
-- Covers queries filtering on local_deleted, replacing standalone ix_recordings_local_deleted.
CREATE INDEX ix_recordings_analysis_pending
ON recordings (time ASC)
WHERE local_deleted = false;

-- Upload polling (v0.6.0): Cloud-Sync-Worker finds un-uploaded, non-deleted recordings.
-- Covers queries filtering on uploaded + local_deleted, replacing standalone ix_recordings_uploaded.
CREATE INDEX ix_recordings_upload_pending
ON recordings (time ASC)
WHERE uploaded = false AND local_deleted = false;

-- 9. Detections (Hypertable)
CREATE TABLE detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    recording_id BIGINT NOT NULL,
    worker TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    label TEXT NOT NULL,
    common_name TEXT,
    clip_path TEXT,
    details JSONB NOT NULL,
    PRIMARY KEY (time, id),
    FOREIGN KEY(recording_id) REFERENCES recordings (id)
);
CREATE INDEX ix_detections_time ON detections (time);
CREATE INDEX ix_detections_label ON detections (label);
CREATE INDEX ix_detections_recording_id ON detections (recording_id);
CREATE INDEX ix_detections_worker ON detections (worker);

-- 10. Uploads
CREATE TABLE uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recording_id BIGINT NOT NULL,
    attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    filename TEXT NOT NULL,
    remote_path TEXT,
    size BIGINT NOT NULL,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY(recording_id) REFERENCES recordings (id)
);
CREATE INDEX ix_uploads_recording_id ON uploads (recording_id);
CREATE INDEX ix_uploads_attempt_at ON uploads (attempt_at DESC);

-- 11. TimescaleDB Setup
SELECT create_hypertable('weather', 'time', if_not_exists => TRUE);
SELECT create_hypertable('detections', 'time', if_not_exists => TRUE);
