-- Silvasonic Initial Schema (Consolidated)
-- Replaces Alembic Migrations: 833e0e6f1e08, 20260202_varchar_text

-- 0. Microphone Profiles (New)
CREATE TABLE microphone_profiles (
    slug VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    match_pattern VARCHAR NOT NULL,
    config JSONB NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (slug)
);

-- 1. Devices Table
CREATE TABLE devices (
    name TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL,
    enrollment_status TEXT NOT NULL DEFAULT 'pending',
    last_seen TIMESTAMP WITH TIME ZONE,
    enabled BOOLEAN NOT NULL,
    profile_slug VARCHAR,
    config JSONB NOT NULL,
    PRIMARY KEY (name),
    UNIQUE (serial_number),
    FOREIGN KEY(profile_slug) REFERENCES microphone_profiles (slug)
);

-- 2. System Config
CREATE TABLE system_config (
    key TEXT NOT NULL,
    value JSONB NOT NULL,
    PRIMARY KEY (key)
);

-- 3. System Services
CREATE TABLE system_services (
    name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    status TEXT NOT NULL,
    PRIMARY KEY (name)
);

-- 4. Storage Remotes (Uploader)
CREATE TABLE storage_remotes (
    slug TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    config JSONB NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    target_path TEXT,
    encryption_test TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX ix_storage_remotes_active ON storage_remotes (is_active);

-- 5. Taxonomy
CREATE TABLE taxonomy (
    worker TEXT NOT NULL,
    label TEXT NOT NULL,
    scientific_name TEXT NOT NULL,
    common_names JSONB NOT NULL,
    description JSONB NOT NULL,
    image_path TEXT,
    image_source TEXT,
    conservation_status TEXT,
    PRIMARY KEY (worker, label)
);

-- 6. Weather (Hypertable)
CREATE TABLE weather (
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    source TEXT NOT NULL,
    station_code TEXT,
    temp_c DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    pressure_hpa DOUBLE PRECISION,
    wind_speed_kmh DOUBLE PRECISION,
    wind_gusts_kmh DOUBLE PRECISION,
    precipitation_mm DOUBLE PRECISION,
    cloud_cover INTEGER,
    uv_index DOUBLE PRECISION,
    sunshine_duration DOUBLE PRECISION,
    weather_code INTEGER,
    is_forecast BOOLEAN NOT NULL,
    extra JSONB NOT NULL,
    PRIMARY KEY (time, source)
);

-- 7. Recordings (Hypertable Candidate - but kept as standard table for FK constraints currently)
-- Note: Alembic had create_hypertable commented out because of FK issues. We keep it standard.
CREATE TABLE recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    sensor_id TEXT NOT NULL,
    file_raw TEXT NOT NULL,
    file_processed TEXT NOT NULL,
    duration DOUBLE PRECISION NOT NULL,
    sample_rate INTEGER NOT NULL,
    filesize_raw BIGINT NOT NULL,
    filesize_processed BIGINT NOT NULL,
    uploaded BOOLEAN NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE,
    local_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    analysis_state JSONB NOT NULL,
    upload_info JSONB DEFAULT '{}'::jsonb NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(sensor_id) REFERENCES devices (name)
);
CREATE INDEX ix_recordings_time ON recordings (time);
CREATE INDEX ix_recordings_sensor_id ON recordings (sensor_id);
CREATE INDEX ix_recordings_uploaded ON recordings (uploaded);

-- 8. Detections (Hypertable)
CREATE TABLE detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    recording_id BIGINT NOT NULL,
    worker TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    label TEXT NOT NULL,
    common_name TEXT,
    details JSONB NOT NULL,
    PRIMARY KEY (time, id),
    FOREIGN KEY(recording_id) REFERENCES recordings (id)
);
CREATE INDEX ix_detections_time ON detections (time);
CREATE INDEX ix_detections_label ON detections (label);
CREATE INDEX ix_detections_recording_id ON detections (recording_id);
CREATE INDEX ix_detections_worker ON detections (worker);

-- 9. Uploads
CREATE TABLE uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recording_id BIGINT NOT NULL,
    remote_slug TEXT NOT NULL,
    attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    filename TEXT NOT NULL,
    size BIGINT NOT NULL,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY(recording_id) REFERENCES recordings (id),
    FOREIGN KEY(remote_slug) REFERENCES storage_remotes (slug)
);
CREATE INDEX ix_uploads_recording_id ON uploads (recording_id);
CREATE INDEX ix_uploads_remote_slug ON uploads (remote_slug);

-- 10. TimescaleDB Setup
SELECT create_hypertable('weather', 'time', if_not_exists => TRUE);
SELECT create_hypertable('detections', 'time', if_not_exists => TRUE);
