"""initial_schema_timescaledb.

Revision ID: 833e0e6f1e08
Revises:
Create Date: 2026-02-01 14:28:52.153275

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "833e0e6f1e08"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Run migration upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_table(
        "system_config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "system_services",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "taxonomy",
        sa.Column("worker", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("scientific_name", sa.String(), nullable=False),
        sa.Column("common_names", sa.JSON(), nullable=False),
        sa.Column("description", sa.JSON(), nullable=False),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("image_source", sa.String(), nullable=True),
        sa.Column("conservation_status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("worker", "label"),
    )
    op.create_table(
        "weather",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("station_code", sa.String(), nullable=True),
        sa.Column("temp_c", sa.Float(), nullable=True),
        sa.Column("humidity", sa.Float(), nullable=True),
        sa.Column("pressure_hpa", sa.Float(), nullable=True),
        sa.Column("wind_speed_kmh", sa.Float(), nullable=True),
        sa.Column("wind_gusts_kmh", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("cloud_cover", sa.Integer(), nullable=True),
        sa.Column("uv_index", sa.Float(), nullable=True),
        sa.Column("sunshine_duration", sa.Float(), nullable=True),
        sa.Column("weather_code", sa.Integer(), nullable=True),
        sa.Column("is_forecast", sa.Boolean(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("time", "source"),
    )
    op.create_table(
        "recordings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("file_raw", sa.String(), nullable=False),
        sa.Column("file_processed", sa.String(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("filesize_raw", sa.BigInteger(), nullable=False),
        sa.Column("filesize_processed", sa.BigInteger(), nullable=False),
        sa.Column("uploaded", sa.Boolean(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("analysis_state", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["devices.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recordings_time"), "recordings", ["time"], unique=False)
    op.create_index(op.f("ix_recordings_sensor_id"), "recordings", ["sensor_id"], unique=False)
    op.create_index(op.f("ix_recordings_uploaded"), "recordings", ["uploaded"], unique=False)

    op.create_table(
        "detections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recording_id", sa.BigInteger(), nullable=False),
        sa.Column("worker", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("common_name", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("time", "id"),
    )
    op.create_index(op.f("ix_detections_time"), "detections", ["time"], unique=False)
    op.create_index(op.f("ix_detections_label"), "detections", ["label"], unique=False)
    op.create_index(
        op.f("ix_detections_recording_id"), "detections", ["recording_id"], unique=False
    )
    op.create_index(op.f("ix_detections_worker"), "detections", ["worker"], unique=False)

    op.create_table(
        "uploads",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("recording_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_uploads_recording_id"), "uploads", ["recording_id"], unique=False)

    # --- TimescaleDB Hypertable Setup ---
    # We must convert these tables to hypertables after creation.
    # The extension 'timescaledb' is assumed to be enabled via init.sql (Phase 1).
    op.execute("SELECT create_hypertable('weather', 'time');")
    # op.execute("SELECT create_hypertable('recordings', 'time');") # DISABLED: Cannot serve as FK target if Hypertable
    op.execute("SELECT create_hypertable('detections', 'time');")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Run migration downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploads_recording_id"), table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_detections_worker"), table_name="detections")
    op.drop_index(op.f("ix_detections_recording_id"), table_name="detections")
    op.drop_index(op.f("ix_detections_label"), table_name="detections")
    op.drop_index(op.f("ix_detections_time"), table_name="detections")
    op.drop_table("detections")
    op.drop_index(op.f("ix_recordings_uploaded"), table_name="recordings")
    op.drop_index(op.f("ix_recordings_sensor_id"), table_name="recordings")
    op.drop_index(op.f("ix_recordings_time"), table_name="recordings")
    op.drop_table("recordings")
    op.drop_table("weather")
    op.drop_table("taxonomy")
    op.drop_table("system_services")
    op.drop_table("system_config")
    op.drop_table("devices")
    # ### end Alembic commands ###
