#!/usr/bin/env python3
"""Initialize the Silvasonic development environment.

Relies on common.py for styling and OS-level operations.
"""

import contextlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

from common import (
    Colors,
    check_group_membership,
    ensure_dir,
    get_workspace_path,
    print_banner,
    print_error,
    print_header,
    print_step,
    print_success,
    print_warning,
    run_command,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = Path(__file__).resolve().parent


def load_workspace_dirs() -> list[str]:
    """Load workspace subdirectory paths from workspace_dirs.txt.

    Returns a list of relative path strings (e.g. ['controller', 'recorder']).
    Lines starting with '#' and blank lines are ignored.
    """
    config_file = SCRIPTS_DIR / "workspace_dirs.txt"
    if not config_file.exists():
        print_error(f"Workspace directory config not found: {config_file}")
        sys.exit(1)

    dirs: list[str] = []
    for line in config_file.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        dirs.append(stripped)
    return dirs


def ensure_env_file() -> None:
    """Ensure .env exists, created from .env.example if necessary."""
    env_file = PROJECT_ROOT / ".env"
    env_example = PROJECT_ROOT / ".env.example"

    # .env.example MUST exist - it's the canonical template
    if not env_example.exists():
        print_error(".env.example not found - cannot bootstrap environment. Aborting!")
        sys.exit(1)

    if env_file.exists():
        print_success(f".env already exists: {env_file}")
    else:
        shutil.copy2(env_example, env_file)
        print_warning("Created .env from .env.example - please review and adjust values!")

    # Auto-generate and inject a secure encryption key if missing or empty
    env_content = env_file.read_text(encoding="utf-8")

    # Check if key is completely missing or empty/commented out
    import base64
    import re

    if not re.search(r"^SILVASONIC_ENCRYPTION_KEY=.+", env_content, re.MULTILINE):
        new_key = base64.urlsafe_b64encode(os.urandom(32)).decode("utf-8")

        # Try to replace the commented/empty placeholder first
        if re.search(r"^[#\s]*SILVASONIC_ENCRYPTION_KEY=.*$", env_content, re.MULTILINE):
            env_content = re.sub(
                r"^[#\s]*SILVASONIC_ENCRYPTION_KEY=.*$",
                f'SILVASONIC_ENCRYPTION_KEY="{new_key}"',
                env_content,
                flags=re.MULTILINE,
            )
        else:
            # Append if not found at all
            env_content += (
                f'\n\n# Auto-generated by just setup\nSILVASONIC_ENCRYPTION_KEY="{new_key}"\n'
            )

        env_file.write_text(env_content, encoding="utf-8")
        print_success("Auto-generated new SILVASONIC_ENCRYPTION_KEY in .env")

    # Cleanup stale host config variables
    cleaned_env_content = env_content
    for stale_var in ["HOST_AUDIO_GID", "HOST_SELINUX"]:
        if re.search(rf"^{stale_var}=.*$", cleaned_env_content, re.MULTILINE):
            cleaned_env_content = re.sub(
                rf"^({stale_var}=.*)$",
                r"# \1  # Removed by setup (deprecated)",
                cleaned_env_content,
                flags=re.MULTILINE,
            )
    if cleaned_env_content != env_content:
        env_file.write_text(cleaned_env_content, encoding="utf-8")
        print_warning("Cleaned up deprecated host configuration variables from .env")
        env_content = cleaned_env_content

    # Auto-patch UID in Podman socket paths (cross-distro portability)
    # .env.example ships with UID 1000 as a reasonable default, but the
    # actual UID may differ on enterprise distros or after user re-creation.
    actual_uid = str(os.getuid())
    if actual_uid != "1000" and "/run/user/1000/" in env_content:
        patched = env_content.replace("/run/user/1000/", f"/run/user/{actual_uid}/")
        env_file.write_text(patched, encoding="utf-8")
        print_success(f"Patched Podman socket paths: UID 1000 → {actual_uid}")


def ensure_override_template() -> None:
    """Ensure config/defaults.override.yml exists as a template if missing."""
    override_file = PROJECT_ROOT / "config" / "defaults.override.yml"
    defaults_file = PROJECT_ROOT / "config" / "defaults.yml"

    if override_file.exists():
        print_success(f"Override template already exists: {override_file}")
        return

    # Create directory just in case it's missing
    override_file.parent.mkdir(parents=True, exist_ok=True)

    header = """\
# ==============================================================================
# Local Override Configuration
# ==============================================================================
# This file is intentionally ignored by git (.gitignore).
# Use it to safely override internal application defaults during local development,
# without risking accidental commits of your local test settings.
#
# Uncomment and adjust the values below to activate overrides:
# ==============================================================================

"""

    defaults_content = defaults_file.read_text(encoding="utf-8")
    commented_defaults = "\n".join(
        f"# {line}" if line.strip() else "" for line in defaults_content.splitlines()
    )

    override_file.write_text(header + commented_defaults + "\n", encoding="utf-8")
    print_warning(f"Created local override template at {override_file.relative_to(PROJECT_ROOT)}")


def check_container_engine() -> None:
    """Verify that Podman is available. Abort if not."""
    if not shutil.which("podman"):
        print_error(
            "Container engine 'podman' not found in PATH!\n"
            "   Install podman: https://podman.io/docs/installation\n"
            "   Container commands (just build/start/stop) require a working engine."
        )
        sys.exit(1)

    print_success("Container engine 'podman' found.")

    # Check version >= 4.0
    try:
        result = subprocess.run(["podman", "--version"], capture_output=True, text=True, check=True)
        version_str = result.stdout.strip().split()[2]  # typically "podman version x.y.z"
        major_version = int(version_str.split(".")[0])
        if major_version < 4:
            print_warning(
                f"Podman version {version_str} is < 4.0. "
                "This may cause issues with rootless privileged containers."
            )
    except Exception as e:
        print_warning(f"Could not determine Podman version: {e}")


def check_linger() -> None:
    """Check if loginctl enable-linger is active."""
    if not shutil.which("loginctl"):
        return

    try:
        result = subprocess.run(
            ["loginctl", "show-user", os.environ.get("USER", "root"), "--property=Linger"],
            capture_output=True,
            text=True,
        )
        if "Linger=yes" not in result.stdout:
            print_warning("User linger is not enabled. Background services will stop on logout.")
            print_error("PLEASE FIX: Run the following command:")
            print(f"{Colors.BOLD}loginctl enable-linger $USER{Colors.ENDC}")
        else:
            print_success("User linger is enabled.")
    except Exception as e:
        print_warning(f"Could not check linger status: {e}")


def main() -> None:
    """Main initialization routine."""
    print_banner()
    print_header("Initializing Silvasonic Development Environment")

    # 1. Environment File & Config Templates
    print_step("Checking .env file & Config overrides...")
    ensure_env_file()
    ensure_override_template()

    # 2. Container Engine
    print_step("Checking container engine availability...")
    check_container_engine()

    # 2b. User Session Configuration
    print_step("Checking User Session Configuration...")
    check_linger()

    # 3. Dependency Sync (uv)
    print_step("Syncing dependencies (uv)...")
    if not shutil.which("uv"):
        print_error(
            "'uv' is not installed!\n"
            "   Install via:  curl -LsSf https://astral.sh/uv/install.sh | sh\n"
            "   Then restart your shell and re-run:  just setup"
        )
        sys.exit(1)

    run_command(["uv", "sync"])
    print_success("Dependencies synced and virtual environment created.")

    # 4. Git Hooks
    print_step("Installing Pre-Commit Hooks...")
    run_command(
        [
            "uv",
            "run",
            "pre-commit",
            "install",
            "--hook-type",
            "pre-commit",
            "--hook-type",
            "pre-push",
        ]
    )
    print_success("Git hooks installed.")

    # 5. Workspace Setup (Two-Worlds Architecture)
    print_step("Setting up Workspace (Two-Worlds Architecture)...")
    workspace_dir = get_workspace_path()

    # Create workspace root
    ensure_dir(workspace_dir)

    # Create all subdirectories from external config
    workspace_dirs = load_workspace_dirs()
    for d in workspace_dirs:
        folder_path = ensure_dir(workspace_dir / d)
        print(f"   Created/Verified: {folder_path}")

    print_success(f"Workspace ready at: {workspace_dir} (Permissions: 755)")

    # 5b. Podman Socket Verification
    # The socket file can vanish after service idle-timeout while systemd
    # still reports the unit as "listening" (stale kernel FD).  A restart
    # of the socket unit re-materialises the .sock file reliably.
    print_step("Verifying Podman user socket...")
    socket_path = Path(f"/run/user/{os.getuid()}/podman/podman.sock")

    if not socket_path.exists() and shutil.which("systemctl"):
        # Attempt to (re-)activate the socket unit
        with contextlib.suppress(subprocess.TimeoutExpired, FileNotFoundError):
            subprocess.run(
                ["systemctl", "--user", "restart", "podman.socket"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=10,
            )

    if socket_path.exists():
        print_success(f"Podman socket active: {socket_path}")
    else:
        warn = Colors.WARNING
        bold = Colors.BOLD
        end = Colors.ENDC
        print(f"   ⚠️  Podman user socket not found: {socket_path}")
        print(f"      {warn}Required for integration tests and Tier 2 containers.{end}")
        print(f"      {bold}Fix: systemctl --user enable --now podman.socket{end}")

    # 6. Hardware Access Verification (cross-distro)
    # Only audio (ALSA) and dialout (USB serial) are universally needed.
    # RPi-specific groups like gpio/spi/i2c are NOT required by Silvasonic.
    # With privileged containers, group membership is sufficient — no ACL probing needed.
    print_step("Verifying Hardware Access Groups...")
    required_groups = ["audio", "dialout"]
    not_configured = []

    user = os.environ.get("USER", "root")

    for group in required_groups:
        exists, is_in_db, is_active = check_group_membership(group, user)

        if not exists:
            print(f"   (i) Group '{group}' does not exist on this system (skipped)")
        elif is_active or is_in_db:
            print(f"   ✅ User '{user}' is in '{group}'")
        else:
            print(f"   ⚠️  WARNING: User '{user}' is NOT in '{group}'.")
            not_configured.append(group)

    if not_configured:
        print_error("PLEASE FIX: Run the following command, then re-login:")
        print(f"{Colors.BOLD}sudo usermod -aG {','.join(not_configured)} {user}{Colors.ENDC}")
        print(f"   Then: {Colors.WARNING}Log out and log back in (or reboot){Colors.ENDC}")
    else:
        print_success("Hardware group verification passed.")

    print_header("Initialization Complete! 🎉")
    print_banner()


if __name__ == "__main__":
    main()
